"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionRunMode = "action-run-mode";
exports.ActionRunModeTimeMinutes = "action-run-mode-time-minutes";
exports.imageTemplateName = exports.containerName = exports.storageAccountName = exports.DistImageTags = exports.RunOutputName = exports.DistLocation = exports.DistResourceId = exports.DistributeType = exports.customizerDestination = exports.customizerScript = exports.customizerWindowsUpdate = exports.WindowsUpdateProvisioner = exports.InlineScript = exports.CustomizerSource = exports.sharedImageGallerySourceTypeImage = exports.managedImageSourceTypeImage = exports.marketPlaceSourceTypeImage = exports.platformImageSourceTypeImage = exports.SourceImage = exports.SourceOSType = exports.SourceImageType = exports.ManagedIdentity = exports.VMSize = exports.BuildTimeoutInMinutes = exports.ImageBuilderTemplateName = exports.ResourceGroupName = exports.Location = void 0;
exports.Location = "location";
exports.ResourceGroupName = "resource-group-name";
exports.ImageBuilderTemplateName = "image-builder-template-name";
exports.BuildTimeoutInMinutes = "build-timeout-in-minutes";
exports.VMSize = "vm-size";
exports.ManagedIdentity = "managed-identity";
exports.SourceImageType = "source-image-type";
exports.SourceOSType = "source-os-type";
exports.SourceImage = "source-image";
exports.platformImageSourceTypeImage = "platformimage";
exports.marketPlaceSourceTypeImage = "marketplace";
exports.managedImageSourceTypeImage = "managedimage";
exports.sharedImageGallerySourceTypeImage = "SharedImageGallery";
exports.CustomizerSource = "customizer-source";
exports.InlineScript = "inlineScript";
exports.WindowsUpdateProvisioner = "windowsUpdateProvisioner";
exports.customizerWindowsUpdate = "customizer-windows-update";
exports.customizerScript = "customizer-script";
exports.customizerDestination = "customizer-destination";
exports.DistributeType = "dist-type";
exports.DistResourceId = "dist-resource-id";
exports.DistLocation = "dist-location";
exports.RunOutputName = "run-output-name";
exports.DistImageTags = "dist-image-tags";
exports.storageAccountName = "strgacc";
exports.containerName = "imagebuilder-aib-action";
exports.imageTemplateName = "imagebuilderTemplate_";
