name: Build system to single file

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'Install required packages'
        shell: bash
        run: |
          cd ${{ GITHUB.WORKSPACE }}/
          npm install
          npm i -g @vercel/ncc

      - name: 'Build Project'
        shell: bash
        run: |
          cd ${{ GITHUB.WORKSPACE }}/
          ncc build lib/index.js --license LICENSE

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      # git pull is needed on push because this is a PR
      # origin HEAD:${{ github.head_ref }} is needed on push because this is a PR
      - name: Commit Build file changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config pull.rebase true
          git pull origin HEAD:${{ github.head_ref }} 
          git config --global user.name 'Azure Image Builder Bot'
          git config --global user.email 'azure-image-builder-bot@users.noreply.github.com'
          git commit -am "Auto Build GH Action"
          git push origin HEAD:${{ github.head_ref }}
          